# Welcome to Serverless!


service: Sample-MobileFlows-Serverless-Connector 

# List of plugins to be used
plugins:
  - serverless-offline

custom:
    authorizer:
        arn: arn:aws:lambda:us-east-1:485793342887:function:SampleJwtAuthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
        identityValidationExpression: '.*'


provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev


  apiGateway:
    binaryMediaTypes:
      - '*/*'

  
functions:
  app:
    handler: connector.server 
    events: 
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /images/{any+}
          method: GET
          cors: true   
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          authorizer: ${self:custom.authorizer}
